//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace IS.SIP2.Cloud.ncip {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NCIPVersionMessage {
        
        private object itemField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LookupVersion", typeof(LookupVersion))]
        [System.Xml.Serialization.XmlElementAttribute("LookupVersionResponse", typeof(LookupVersionResponse))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LookupVersion {
        
        private FromAgencyId fromAgencyIdField;
        
        private ToAgencyId toAgencyIdField;
        
        /// <remarks/>
        public FromAgencyId FromAgencyId {
            get {
                return this.fromAgencyIdField;
            }
            set {
                this.fromAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        public ToAgencyId ToAgencyId {
            get {
                return this.toAgencyIdField;
            }
            set {
                this.toAgencyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FromAgencyId {
        
        private UniqueAgencyId uniqueAgencyIdField;
        
        /// <remarks/>
        public UniqueAgencyId UniqueAgencyId {
            get {
                return this.uniqueAgencyIdField;
            }
            set {
                this.uniqueAgencyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UniqueAgencyId {
        
        private string schemeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ToAgencyId {
        
        private UniqueAgencyId uniqueAgencyIdField;
        
        /// <remarks/>
        public UniqueAgencyId UniqueAgencyId {
            get {
                return this.uniqueAgencyIdField;
            }
            set {
                this.uniqueAgencyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LookupVersionResponse {
        
        private FromAgencyId fromAgencyIdField;
        
        private ToAgencyId toAgencyIdField;
        
        private string[] versionSupportedField;
        
        /// <remarks/>
        public FromAgencyId FromAgencyId {
            get {
                return this.fromAgencyIdField;
            }
            set {
                this.fromAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        public ToAgencyId ToAgencyId {
            get {
                return this.toAgencyIdField;
            }
            set {
                this.toAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VersionSupported")]
        public string[] VersionSupported {
            get {
                return this.versionSupportedField;
            }
            set {
                this.versionSupportedField = value;
            }
        }
    }
}
